### ISSUE TITLE
`prop-types` has been removed in v5.5.3

### ISSUE THREAD

**Issue by craftzdog** [jmerle/inkdrop-plantuml#11]
Hi Jasper! How are you?

I've recently dropped `prop-types` from the app and that causes the issue in this plugin.

https://github.com/jmerle/inkdrop-plantuml/blob/master/src/PlantUML.jsx#L4

You can simply stop using prop-types to fix it.

**Comment by jmerle** [comment]
Fixed in f43645c5b443f4a705fa69c7c1d95c7fcdd90bcc, will be released within an hour. Thanks for letting me know!
